Greg profile mvp
AGawrys/CodeUSpring2018 pull request #10
Opened 2018-05-28 07:46 UTC by Gfranklin20

This pull request also has a slight change to the chat portion so that users can now enter a bunch of more tags in the chat box

2018-05-29 02:48 UTC, AGawrys commented on src/main/java/codeu/controller/ProfileServlet.java
> +
Remember to keep spacing consistent.

2018-05-29 13:03 UTC, bandreasv reviewed
Overall this pull requests is good. My only big concern is that this is too big of a pull request. Try to keep your pull request smaller.

2018-05-30 00:57 UTC, AGawrys commented on src/main/java/codeu/controller/ProfileServlet.java
> +              //request.setAttribute("AboutMe", about);
Make sure to remove any unnecessary commented out code.

2018-05-30 01:00 UTC, AGawrys requested changes
Good amount of code for a pull request, and it is clean. Nice! If you're having trouble with storing the About me data, have you tried maybe making it an attribute of a user? So that data could be stored when a user is created and then simply updated or changed? Not sure. Maybe fix that issue first before merging the branch into master.

2018-06-05 02:42 UTC, merged